---
title: "README"
author: "Zixuan Yu"
output: md_document
---
--------------------------------------------------------------------------------  

### 2. R Programming
instructor: Roger D Peng    
course link: https://www.coursera.org/learn/r-programming  
&#x1F6A6; started: 2021/05/01      
&#x1F389; finished: 2021/06/29  
&#x1F3C5; [certificate](https://coursera.org/share/ca90a0c5642a0b6a026b7a2331873643)  
  
#### Notes, Assignments and Projects  

* [&#x1F680; Course Project 1 Repositoary: Matrix Calculation ](https://github.com/Zixuan-YU/ProgrammingAssignment2)  
* [&#x1F680; Course Project 2 Air Pollution]()
* [&#x1F680; Course Project 3 Hospital Mortality]()
* [&#x1F4DD; Quiz 1]()
* [&#x1F4DD; Quiz 2]()

--------------------------------------------------------------------------------

#### Class Notes

* [&#x1F4D2; Week 2](./2.R_Programming/RProgramming_week2_notes2.md)    
* [&#x1F4D2; Week 3](./2.R_Programming/RProgramming_week3_notes.R)  

--------------------------------------------------------------------------------

#### Course Description
In this course you will learn how to program in R and how to use R for effective data analysis. You will learn how to install and configure software necessary for a statistical programming environment and describe generic programming language concepts as they are implemented in a high-level statistical language. The course covers practical issues in statistical computing which includes programming in R, reading data into R, accessing R packages, writing R functions, debugging, profiling R code, and organizing and commenting R code. Topics in statistical data analysis will provide working examples.  

#### Course Syllabus
- Week 1: Background, Getting Started, and Nuts & Bolts
- Week 2: Programming with R  
- Week 3: Loop Functions and Debugging  
- Week 4: Simulation & Profiling  

#### Course Textbook

[&#x1F4D6; R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/)


--------------------------------------------------------------------------------  

### 3. Getting and Cleaning Data
instructor: Jeff Leek, PhD,   Roger D. Peng, PhD, Brian Caffo, PhD       
course link: [Getting and Cleaning Data](https://www.coursera.org/learn/data-cleaning)      
&#x1F6A6; started: 2021/02/14        
&#x1F389; finished: 2022/03/02    
&#x1F3C5; [certificate]()  
  
#### Notes, Assignments and Projects  

* [&#x1F680; Course Project 1 Repositoary: Matrix Calculation ](https://github.com/Zixuan-YU/ProgrammingAssignment2)    
* [&#x1F680; Course Project 2: Air Pollution]()  
* [&#x1F680; Course Project 3: Hospital Mortality]()  
* [&#x1F4DD; Quiz 1](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/2.Getting_and_Cleaning_Data/week1_quiz.R)  
* [&#x1F4DD; Quiz 2](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/2.Getting_and_Cleaning_Data/week2_quiz.R)  
* [&#x1F4DD; Quiz 3](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/2.Getting_and_Cleaning_Data/week3_quiz.R)  
* [&#x1F4DD; Quiz 4](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/2.Getting_and_Cleaning_Data/week4_quiz.Rmd)  

--------------------------------------------------------------------------------

#### Class Notes

* [&#x1F4D2; Week 1](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/2.Getting_and_Cleaning_Data/week1_notes.md)    
* [&#x1F4D2; Week 2](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/2.Getting_and_Cleaning_Data/week2_notes.R)  

--------------------------------------------------------------------------------

#### Course Description
Before you can work with data you have to get some. This course will cover the basic ways that data can be obtained. The course will cover obtaining data from the web, from APIs, from databases and from colleagues in various formats. It will also cover the basics of data cleaning and how to make data “tidy”. Tidy data dramatically speed downstream data analysis tasks. The course will also cover the components of a complete data set including raw data, processing instructions, codebooks, and processed data. The course will cover the basics needed for collecting, cleaning, and sharing data.    

#### Course Syllabus
- Data collection
  * Raw files (.csv,.xlsx)
  * Databases (mySQL,MongoDB)
  * APIs
- Data formats
  * Flat files (.csv,.txt)
  * XML
  * JSON
- Making data tidy
- Distributing data
- Scripting for data cleaning

#### Course Textbook

[&#x1F4D6; Tidyverse Skills for Data Science in R](https://leanpub.com/tidyverseskillsdatascience)


--------------------------------------------------------------------------------  

### 4. Exploratery Data Analysis 
instructor: Jeff Leek, PhD,   Roger D. Peng, PhD, Brian Caffo, PhD         
course link: [Exploratery Data Analysis](https://www.coursera.org/learn/exploratory-data-analysis)    

#### Notes, Assignments and Projects   
 &#x1F6A6; start: 2022/07/02  
 &#x1F389; finish:   

* [&#x1F680; Course Project 1: Power Consumption](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/4.Exploratory_Data_Analysis/EDA_week1_project1_power_consumption.md)  
* [&#x1F680; Course Project 2 Repository]
* [&#x1F4DD; Quiz 1](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/4.Exploratory_Data_Analysis/EDA_week1_quiz.md)
* [&#x1F4DD; Quiz 2](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/4.Exploratory_Data_Analysis/EDA_week2_quiz.md)
* [&#x1F4DD; Quiz 2]

--------------------------------------------------------------------------------

#### Class Notes

* [&#x1F4D2; Week 1]
* [&#x1F4D2; Week 2]


--------------------------------------------------------------------------------

#### Course Description

 In this course you will learn the ideas of reproducible research and reporting of statistical analyses. Topics covered include literate programming tools, evidence-based data analysis, and organizing data analyses. In this course you will learn to write a document using R markdown, integrate live R code into a literate statistical program, compile R markdown documents using knitr and related tools, publish reproducible documents to the web, and organize a data analysis so that it is reproducible and accessible to others.

#### Course Syllabus
- Making exploratory graphs

- Principles of analytic graphics

- Plotting systems and graphics devices in R

- The base, lattice, and ggplot2 plotting systems in R

- Clustering methods

- Dimension reduction techniques


#### Course Textbook

 [&#x1F4D6; Exploratory Data Analysis with R](https://leanpub.com/exdata)  


--------------------------------------------------------------------------------  

### 5.Reproducible Research
instructor: Roger D Peng    
course link: "https://www.coursera.org/learn/reproducible-research"    
  
#### Notes, Assignments and Projects  
 &#x1F6A6; start: 2022/07/02  
 &#x1F389; finish:   

* [&#x1F680; Course Project 1: Daily Activity Pattern ](https://github.com/Zixuan-YU/datasciencecoursera/blob/main/5.Reproducible_Research/PA1_template.md)  
* [&#x1F680; Course Project 2 Repository]()
* [&#x1F4DD; Quiz 1]()
* [&#x1F4DD; Quiz 2]

--------------------------------------------------------------------------------

#### Class Notes

* [&#x1F4D2; Week 1]( )  
* [&#x1F4D2; Week 2]( )  
* [&#x1F4D2; Week 3]( )  
* [&#x1F4D2; Week 4]( )  


--------------------------------------------------------------------------------

#### Course Description

 In this course you will learn the ideas of reproducible research and reporting of statistical analyses. Topics covered include literate programming tools, evidence-based data analysis, and organizing data analyses. In this course you will learn to write a document using R markdown, integrate live R code into a literate statistical program, compile R markdown documents using knitr and related tools, publish reproducible documents to the web, and organize a data analysis so that it is reproducible and accessible to others.

#### Course Syllabus

* Structuring and organizing a data analysis
* Markdown and R Markdown
* knitr / RPubs
* Reproducible research check list
* Evidence-based data analysis
* Case studies in air pollution epidemiology and high-throughput biology

#### Course Textbook

The book [&#x1F4D6; Report Writing for Data Science in R](https://mth332.files.wordpress.com/2018/01/reportwriting.pdf) covers the lecture material in this course.  

#### Course Projects

The Course Projects focus on plotting and will be assessed via peer assessment. In these assignments, you will be asked to conduct data analysis and you will be evaluated by your classmates on the work and code that you write. Assignments evaluated via peer assessment will make use of your GitHub account or the RPubs web site.