---
title: 'EDA week3 notes: clustering'
author: "Zixuan Yu"
date: "7/5/2022"
output: html_document
---
Textbook: https://bookdown.org/rdpeng/exdata/hierarchical-clustering.html  


#### Hierachical Clustering
The algorithm is recursive and goes as follows:  

- Find closest two things points in your dataset

- Put them together and call them a “point”

- Use your new “dataset” with this new point and repeat

##### Euclidean distance
$$A = (A_1,A_2,...,A_n)$$
$$B = (B_1,B_2,...,B_n)$$
$$Distance = \sqrt{[(A_1-B_1)^2 + (A_2-B_2)^2 + ... + (A_n-B_n)^2]}$$  

##### Manhattan distance
$$Distance = |A_1-B_1| + |A_2-B_2| + ... + |A_n-B_n| $$ 

```{r}
 set.seed(1234)
 x <- rnorm(12, rep(1:3, each = 4), 0.2)
 y <- rnorm(12, rep(c(1, 2, 1), each = 4), 0.2)
 plot(x, y, col = "blue", pch = 19, cex = 2)
 text(x + 0.05, y + 0.05, labels = as.character(1:12))
```



```{r}
d <- data.frame(x=x, y=y)
dist(d)
```

The default distance metric used by the `dist()` function is Euclidean distance.  

```{r}
rdistxy <- as.matrix(dist(d))

## Remove the diagonal from consideration
diag(rdistxy) <- diag(rdistxy) + 100000

ind <- which(rdistxy == min(rdistxy), arr.ind = TRUE)
ind
```



##### heatmap()
```{r}

df <- data.frame(x=x, y=y)
set.seed(143)
dm <- as.matrix(df)[sample(1:12),]
heatmap(dm)

```











